export const smsVerifySuccessResponseDummy = {
  groupInfo: {
    _id: '00000000000000000000000000000000',
    serviceMethod: 'MT',
    apiVersion: 'v4',
    sdkVersion: 'nodejs/5.2.0',
    osPlatform: 'darwin | v18.17.1',
    count: {
      total: 1,
      sentTotal: 0,
      sentFailed: 0,
      sentSuccess: 0,
      sentPending: 0,
      sentReplacement: 0,
      refund: 0,
      registeredFailed: 0,
      registeredSuccess: 1,
    },
    countForCharge: {
      sms: {
        '82': 1,
      },
      lms: {},
      mms: {},
      ata: {},
      cta: {},
      cti: {},
      nsa: {},
      rcs_sms: {},
      rcs_lms: {},
      rcs_mms: {},
      rcs_tpl: {},
      fax: {},
      voice: {},
    },
    log: [
      {
        createAt: new Date().toISOString(),
        message: '[221.138.194.146] 메시지 그룹이 생성되었습니다.',
      },
      {
        createAt: new Date().toISOString(),
        message: '국가코드(82)의 단문 문자(SMS) 1 건이 추가되었습니다.',
      },
      {
        createAt: new Date().toISOString(),
        message: '메시지를 발송했습니다.',
        oldBalance: 9857,
        newBalance: 9844,
        oldPoint: 0,
        newPoint: 0,
        totalPrice: 13,
      },
    ],
    status: 'SENDING',
    dateSent: new Date().toISOString(),
    scheduledDate: null,
    dateCompleted: null,
    balance: {
      requested: 13,
      replacement: 0,
      refund: 0,
      sum: 13,
    },
    point: {
      requested: 0,
      replacement: 0,
      refund: 0,
      sum: 0,
    },
    isRefunded: false,
    app: {
      appId: null,
      version: null,
      profit: {
        sms: 0,
        lms: 0,
        mms: 0,
        ata: 0,
        cta: 0,
        cti: 0,
        nsa: 0,
        rcs_sms: 0,
        rcs_lms: 0,
        rcs_mms: 0,
        rcs_tpl: 0,
        fax: 0,
        voice: 0,
      },
    },
    price: {
      '82': {
        sms: 13,
        lms: 29,
        mms: 70,
        ata: 9,
        cta: 14,
        cti: 22,
        nsa: 9,
        rcs_sms: 15,
        rcs_lms: 32,
        rcs_mms: 80,
        rcs_tpl: 9,
        fax: 100,
        voice: 150,
      },
    },
    flagUpdated: false,
    customFields: {},
    prepaid: true,
    strict: false,
    hint: {},
    masterAccountId: null,
    allowDuplicates: false,
    accountId: '00000000000000',
    groupId: '00000000000000000000000000000000',
    dateCreated: new Date().toISOString(),
    dateUpdated: new Date().toISOString(),
  },
  failedMessageList: [],
};
