#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

function isChanged {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if isChanged 'pnpm-lock.yaml'; then
  echo "!📦pnpm-lock.yaml changed."
    pnpm install
  exit 0
  else 
    echo "📦pnpm-lock.yaml not changed."
fi

if isChanged 'apps/hasura/migrations' || isChanged 'apps/hasura/metadata'; then
  echo "!📦hasura changed."
    pnpm hasura schema
  exit 0
  else
    echo "📦hasura not changed."
fi