name: Nest Mixpanel CI
on:
  pull_request:

jobs:
  everything:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      # - name: Install Doppler CLI
      #   uses: dopplerhq/cli-action@v1

      # - name: Export .env
      #   run: doppler secrets download --no-file --format env-no-quotes > .env
      #   env:
      #     DOPPLER_TOKEN: ${{ secrets.TEST_DOPPLER_TOKEN }}

      - name: Lint Format
        run: pnpm lint:format

      - name: Build Knox-Token-Library
        run: pnpm build

      - name: Type Check
        run: pnpm type-check

      # - name: Test
      #   run: pnpm test:coverage

      - name: Build
        run: pnpm build

      # - name: 'Report Coverage'
      #   uses: davelosert/vitest-coverage-report-action@v2
      #   if: always()
      #   with:
      #     working-directory: packages/knox-api
