name: Nestjs Mixpanel Publish

on:
  push:
    branches:
      - master
    tags:
      - 'nestjs-mixpanel@*'

jobs:
  publish-npm:
    name: Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/nestjs-mixpanel@')
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm i

      - name: Lint Format
        working-directory: packages/nestjs-mixpanel
        run: pnpm lint:format

      - name: Type Check
        working-directory: packages/nestjs-mixpanel
        run: pnpm type-check

      - name: Build
        working-directory: packages/nestjs-mixpanel
        run: pnpm build:production

      - name: Publish to npm
        working-directory: packages/nestjs-mixpanel
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REDREDGROUP_ORGANIZATION_NPM_PUBLISH_KEY }}
